name: Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++ make
        
    - name: Build
      run: make -j
      
    - name: Run tests
      run: make test
      
    - name: Test Summary
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ All tests passed!"
        else
          echo "❌ Tests failed"
          exit 1
        fi
